### ISSUE TITLE
Add missing lists commands

### ISSUE THREAD

**Issue by mijicd** [zio/zio-redis#10]
Keys API currently doesn't support `BLPOP`, `BRPOP` and `LINSERT`. To be able to represent them, our DSL needs to be adjusted to support non-empty lists that aren't in last positions (as well as having multiple non-empty lists).

cc @jdegoes

**Comment by jdegoes** [comment]
`command(input)(varargs1)(varargs2)`

`command(input1)(varargs)(input2)`

Mapping Redis non-empty lists to Scala non-empty lists (first element and then varargs) will require a separate parameter list for each non-empty.

**Comment by anovakovic01** [comment]
@mijicd I can take this one next if no one else is working on it.

**Comment by mijicd** [comment]
@anovakovic01 all yours.
