### ISSUE TITLE
Add missing sorted sets commands

### ISSUE THREAD

**Issue by mijicd** [zio/zio-redis#14]
Sorted sets API currently doesn't support the following:

- [x] `ZINTERSTORE`
- [x]  `ZLEXCOUNT`
- [x]  `ZPOPMAX`
- [x]  `ZPOPMIN`
- [x]  `ZRANGEBYLEX`
- [x]  `ZREVRANGEBYLEX`
- [x]  `ZRANGEBYSCORE`
- [x]  `ZREMRANGEBYLEX`
- [x]  `ZREMRANGEBYRANK`
- [x]  `ZREMRANGEBYSCORE`
- [x]  `ZREVRANGE`
- [x]  `ZREVRANGEBYSCORE`
- [x]  `ZREVRANK`
- [x]  `ZUNIONSTORE`

As there are quite a few of them, please raise your hand for the ones you're tackling :).

**Comment by landlockedsurfer** [comment]
I will start working on this issue.

**Comment by mijicd** [comment]
Closed via #17
