### ISSUE TITLE
Add logging capability

### ISSUE THREAD

**Issue by quelgar** [zio/zio-redis#140]
I don't think we need to go overboard with logging, but it would be useful to log when connections and reconnections are occurring, and why. Once we have Sentinel support we'd also want to log the outcomes of Sentinel discovery.

It might also help users debugging apps if there was an option to log a trace of commands and responses?

Probably [zio-logging](https://github.com/zio/zio-logging) is the way to go.

**Comment by anovakovic01** [comment]
I will take this one.

**Comment by cleliofs** [comment]
> Once we have Sentinel support we'd also want to log the outcomes of Sentinel discovery.
 
Any ETA for when this lib will support Redis Sentinels?
