### ISSUE TITLE
Implement remaining hash commands

### ISSUE THREAD

**Issue by mijicd** [zio/zio-redis#152]
Extracted from [this comment](https://github.com/zio/zio-redis/issues/68#issuecomment-691777714) authored by @regis-leray.

### Commands

- [x] HMSET key field value [field value ...] Set multiple hash fields to multiple values

### Tips

- Define the API in `zio.redis.api`.
- Command-specific options should be defined in `zio.redis.options`.
- Additional inputs and outputs can be defined in `zio.redis.Input` and `zio.redis.Output`, respectively.
- Redis API evolves, therefore the commands listed above might be slightly changed. Double check [the official docs](https://redis.io/commands) before starting with implementation. 
- Use telnet to understand command protocol details.
- Write inputs and outputs tests in `zio.redis.InputSpec` and `zio.redis.OutputSpec`, respectively.
- Write integration tests by expanding the `zio.redis.ApiSpec`.
- If you feel that the pull request size is growing out of control, feel free to split it but make sure to link this issue in each of the related PRs.

**Comment by rfmejia** [comment]
I'm working on this ticket, are my assumptions correct?

- Input type: same as HSET
- Output type: simple string reply from Redis is mapped to `OptionalOutput(UnitOutput)`

Also is there any special handling we need since HMSET is deprecated in Redis 4?

**Comment by anovakovic01** [comment]
> I'm working on this ticket, are my assumptions correct?
> 
> Input type: same as HSET
> Output type: simple string reply from Redis is mapped to OptionalOutput(UnitOutput)

@rfmejia Your assumption in regard to the `HMSET` input type is correct. Output time should be just `UnitOutput`.

> Also is there any special handling we need since HMSET is deprecated in Redis 4?

I think that there is no need for any special handling, except to maybe it as part of scaladoc.

**Comment by mijicd** [comment]
@rfmejia Additionally, you can mark this function as deprecated just to reflect its current status. I was thinking whether to expose it at all, but, it turns out to be still in use :).

Thank you for taking care of this!

**Comment by rfmejia** [comment]
@mijicd I've implemented HMSET and added tests similar to HSET.

One thing I've found was HMGET originally parsed using `Chunk[String]`, but it would throw a `ProtocolError` if the return array contains a "(nil)" when queried with non-existent fields. I changed its parse output type to `Chunk[Option[String]]` where `NullOutput` is represented as a `None` value.

**Comment by rfmejia** [comment]
@mijicd Also, I've added the deprecation notice on its scaladoc. I've tried annotating the function with `@deprecated` but the test will not compile due to the "-Xfatal-warnings" flag. Should I leave it as a scaladoc or remove the compiler flag during testing?

**Comment by mijicd** [comment]
@rfmejia great catch for options. You can remove `@deprecated` completely then. Just a remark in scaladoc is enough.

**Comment by rfmejia** [comment]
@mijicd The PR should be ready for review then, the scaladoc already contains the deprecation notice.

**Comment by mijicd** [comment]
@rfmejia already reviewed :)
