### ISSUE TITLE
Implement pub/sub API

### ISSUE THREAD

**Issue by mijicd** [zio/zio-redis#160]
Extracted from [this comment](https://github.com/zio/zio-redis/issues/68#issuecomment-691777714) authored by @regis-leray.

### Commands

- [ ] PSUBSCRIBE pattern [pattern ...] Listen for messages published to channels matching the given patterns
- [ ] PUBSUB subcommand [argument [argument ...]] Inspect the state of the Pub/Sub subsystem
- [ ] PUBLISH channel message Post a message to a channel
- [ ] PUNSUBSCRIBE [pattern [pattern ...]] Stop listening for messages posted to channels matching the given patterns
- [ ] SUBSCRIBE channel [channel ...] Listen for messages published to the given channels
- [ ] UNSUBSCRIBE [channel [channel ...]] Stop listening for messages posted to the given channels

### Tips

- Define the API in `zio.redis.api`.
- Command-specific options should be defined in `zio.redis.options`.
- Additional inputs and outputs can be defined in `zio.redis.Input` and `zio.redis.Output`, respectively.
- Redis API evolves, therefore the commands listed above might be slightly changed. Double check [the official docs](https://redis.io/commands) before starting with implementation. 
- Use telnet to understand command protocol details.
- Write inputs and outputs tests in `zio.redis.InputSpec` and `zio.redis.OutputSpec`, respectively.
- Write integration tests by expanding the `zio.redis.ApiSpec`.
- If you feel that the pull request size is growing out of control, feel free to split it but make sure to link this issue in each of the related PRs.

**Comment by visox** [comment]
Hi, i can go for it. I probably go from top to bottom but its not that much so if i manage to do one i probably i can make it all.

**Comment by mijicd** [comment]
@visox That sounds good. And I agree, it's perfectly fine to split this one, as you might need to adjust the executor occasionally to support it properly (e.g. separate queue / connection).

**Comment by visox** [comment]
i made WIP pr with some question, plz take a look https://github.com/zio/zio-redis/pull/181 @mijicd 
thx, will continue tomorrow.

**Comment by KadekM** [comment]
@mijicd @anovakovic01 

I'm thinking of tackling this, could you check some rough ideas?

> Once the client enters the subscribed state it is not supposed to issue any other commands, except for additional SUBSCRIBE, PSUBSCRIBE, UNSUBSCRIBE, PUNSUBSCRIBE, PING, RESET and QUIT commands.

I think this state (whether we are subscribed and expect streamed messages or not) should could inside RedisExecutor, and if we are in _subscribed state_ we push to a different `Queue[RespValue]` instead of current promise based one (current resQueue), since we get values pushed in non-request-response fashion.

We'll also probably need to track current _subscriptions_ and _psubscribtions_ (TSet in interpreter prehaps?), so that we know when we leave this streaming state (i.e. subscribe chan1; ... ; unsubscribe chan1) and are back in request-response state. 

Maybe you have some better ideas :-) ?

**Comment by 0pg** [comment]
Hi maybe I can make a PR for this issue

**Comment by mijicd** [comment]
@0pg Go for it!

**Comment by anovakovic01** [comment]
@mijicd should we add a [sharded pub/sub](https://redis.io/docs/manual/pubsub/#sharded-pubsub) as part of this issue, or create a new one for it?

**Comment by mijicd** [comment]
If I'm not mistaken that's a part of 7.x. We could create a dedicated milestone for 7.x as I think there's going to be more differences.
