### ISSUE TITLE
Benchmark list API

### ISSUE THREAD

**Issue by mijicd** [zio/zio-redis#164]
Measure the performance of the most frequently used commands from the list API. Please make sure to benchmark each command using the following client libraries:

- [zio-redis](https://github.com/zio/zio-redis) :)
- [redis4cats](https://github.com/profunktor/redis4cats)
- [laserdisc](https://github.com/laserdisc-io/laserdisc)
- [rediculous](https://github.com/ChristopherDavenport/rediculous)

Since the ticket is "open" in terms of scenarios you can benchmark, make sure to announce your work in the comments so that we can avoid any duplicated work.

### Tips

- Add all benchmarks to the `benchmarks` project.
- Please aim for 10-15 warmup and 10-15 benchmarking iterations. Make sure to submit the results as part of the pull request description.
- Feel free to tackle "low-hanging fruit" optimizations but prefer opening an issue for larger ones.
- Make sure to link the ticket in the pull request description.

**Comment by mvelimir** [comment]
I'll work on this.
