### ISSUE TITLE
Develop testable RedisExecutor

### ISSUE THREAD

**Issue by mijicd** [zio/zio-redis#169]
Design and implement a test Redis executor (check out [this module](https://github.com/zio/zio-redis/blob/master/redis/src/main/scala/zio/redis/Interpreter.scala)).

Ideally, the test executor would execute all of the commands backed by some in-memory structures. I propose to expose the test implementation in the same module via additional layer constructors.

Since this ticket will be involving, I propose to come up with a design proposal and then split the implementation work into API-specific pieces.

**Comment by quelgar** [comment]
Just a minor point while I think of it, the `RespValue.NullValue` will need to be split into two, as RESP actually has two kinds of null: a null bulk string and a null array. These are currently both represented by the same value because a client only ever reads null arrays, it never needs to create them.

**Comment by mschuwalow** [comment]
I'll take this one

**Comment by mijicd** [comment]
The design is provided in #180, closing this in favor of:

- https://github.com/zio/zio-redis/issues/190
- https://github.com/zio/zio-redis/issues/191
- https://github.com/zio/zio-redis/issues/192
- https://github.com/zio/zio-redis/issues/193
- https://github.com/zio/zio-redis/issues/194
- https://github.com/zio/zio-redis/issues/195
- https://github.com/zio/zio-redis/issues/196
- https://github.com/zio/zio-redis/issues/197
- https://github.com/zio/zio-redis/issues/198

**Comment by mschuwalow** [comment]
An initial skeleton has been added. Further work is tracked in the following issues:
- [ ] Connection API - https://github.com/zio/zio-redis/issues/190
- [ ] Geo API - https://github.com/zio/zio-redis/issues/191
- [ ] Hashes API - https://github.com/zio/zio-redis/issues/192
- [ ] HyperLogLog API - https://github.com/zio/zio-redis/issues/193
- [ ] Keys API - https://github.com/zio/zio-redis/issues/194
- [ ] Lists API - https://github.com/zio/zio-redis/issues/195
- [ ] Sets API - https://github.com/zio/zio-redis/issues/196
- [ ] SortedSets API - https://github.com/zio/zio-redis/issues/197
- [ ] Strings API - https://github.com/zio/zio-redis/issues/198
