### ISSUE TITLE
Document lists API

### ISSUE THREAD

**Issue by mijicd** [zio/zio-redis#176]
The current lists API (see `zio.redis.api.Lists`) exposes functions with argument names that are generic and meaningless. I propose to rename those to match those used in the [official documentation](https://redis.io/commands). Additionally, it would be great to provide a small, single-sentence scaladoc for them.

**Comment by helanto** [comment]
I can take this one

**Comment by mijicd** [comment]
@helanto all yours!

**Comment by anovakovic01** [comment]
In order to be consistent, I suggest that all scaladoc comments include `@param` and `@return` (where return value exists).
Here is an example:
```scala
/** Creates a person with a given name and birthdate
 *
 *  @param name their name
 *  @param birthDate the person's birthdate
 *  @return a new Person instance with the age determined by the
 *          birthdate and current date.
 */
def apply(name: String, birthDate: java.util.Date) = {}
```

For more details check [documentation](https://docs.scala-lang.org/style/scaladoc.html).
