### ISSUE TITLE
Document strings API

### ISSUE THREAD

**Issue by mijicd** [zio/zio-redis#179]
The current strings API (see `zio.redis.api.Strings`) exposes functions with argument names that are generic and meaningless. I propose to rename those to match those used in the [official documentation](https://redis.io/commands). Additionally, it would be great to provide a small, single-sentence scaladoc for them.

**Comment by justinhj** [comment]
I am starting on this

**Comment by justinhj** [comment]
https://github.com/zio/zio-redis/pull/183

**Comment by anovakovic01** [comment]
In order to be consistent, I suggest that all scaladoc comments include `@param` and `@return` (where return value exists).
Here is an example:
```scala
/** Creates a person with a given name and birthdate
 *
 *  @param name their name
 *  @param birthDate the person's birthdate
 *  @return a new Person instance with the age determined by the
 *          birthdate and current date.
 */
def apply(name: String, birthDate: java.util.Date) = {}
```

For more details check [documentation](https://docs.scala-lang.org/style/scaladoc.html).

**Comment by justinhj** [comment]
I’ve followed this recommendation from the guidelines btw 

Try to format the first sentence of a method as “Returns XXX”, as in “Returns the first element of the List”, as opposed to “this method returns” or “get the first” etc. Methods typically return things.
