### ISSUE TITLE
Add connection api to test executor

### ISSUE THREAD

**Issue by mschuwalow** [zio/zio-redis#190]
The [test executor](https://github.com/zio/zio-redis/blob/master/redis/src/main/scala/zio/redis/Interpreter.scala#L80) currently only supports a subset of the api.
The goal of this issue is to support the full connection api in the test executor. Tests should be added for all commands that are not currently being tested.

**Comment by jxnu-liguobin** [comment]
I picked it up

**Comment by mijicd** [comment]
Closed by @jxnu-liguobin in #294
