### ISSUE TITLE
Add keys api to test executor

### ISSUE THREAD

**Issue by mschuwalow** [zio/zio-redis#194]
The [test executor](https://github.com/zio/zio-redis/blob/master/redis/src/main/scala/zio/redis/Interpreter.scala#L80) currently only supports a subset of the api.
The goal of this issue is to support the full keys api in the test executor. Tests for this group should be enabled for the test executor [here](https://github.com/zio/zio-redis/blob/master/redis/src/test/scala/zio/redis/ApiSpec.scala#L32)

**Comment by mijicd** [comment]
Closed in #480
