### ISSUE TITLE
Add sets api to test executor

### ISSUE THREAD

**Issue by mschuwalow** [zio/zio-redis#196]
The [test executor](https://github.com/zio/zio-redis/blob/master/redis/src/main/scala/zio/redis/Interpreter.scala#L80) currently only supports a subset of the api.
The goal of this issue is to support the full sets api in the test executor. Tests for this group should be enabled for the test executor [here](https://github.com/zio/zio-redis/blob/master/redis/src/test/scala/zio/redis/ApiSpec.scala#L32)

**Comment by mschuwalow** [comment]
I'm taking this one

**Comment by mschuwalow** [comment]
Most of the API is done, feel free to do the remaining ones.

For [SRANDMEMBER](https://redis.io/commands/srandmember) we probably want something similar to [TRandom](https://github.com/zio/zio-keeper/blob/master/keeper/src/main/scala/zio/keeper/hyparview/TRandom.scala) in keeper

**Comment by helanto** [comment]
@mschuwalow I can try to implement the remaining parts
