### ISSUE TITLE
Support strings api in test executor

### ISSUE THREAD

**Issue by mschuwalow** [zio/zio-redis#198]
The [test executor](https://github.com/zio/zio-redis/blob/master/redis/src/main/scala/zio/redis/Interpreter.scala#L80) currently only supports a subset of the api.
The goal of this issue is to support the full strings api in the test executor. Tests for this group should be enabled for the test executor [here](https://github.com/zio/zio-redis/blob/master/redis/src/test/scala/zio/redis/ApiSpec.scala#L32)

**Comment by asjad02** [comment]
@mijicd picking this up

**Comment by mijicd** [comment]
@asjad02 all yours, thanks for tackling it :pray:

**Comment by hcwilhelm** [comment]
@asjad02 are you still on it? Would it be ok if I take that over?

**Comment by asjad02** [comment]
@hcwilhelm  unfortunately unable to work on the issue. You can go ahead.

**Comment by hcwilhelm** [comment]
@asjad02 @mijicd Ok then I am going to work on Strings API support
