### ISSUE TITLE
Develop an example application

### ISSUE THREAD

**Issue by mijicd** [zio/zio-redis#202]
Create a small HTTP service that fetches contributors to the specified project.

### API

- Endpoint: `/owners/{owner}/projects/{project}/contributors`
- Method: **GET**
- Response codes:
  - 200 with list of contributors if it succeeds
  - 404 if no resource exists
  - 500 for all other errors
- Response body:

```json
{"user":"...", "contributions":"..."}
```

### Tech stack

- akka-http or http4s
- sttp
- zio-json
- zio-redis :)
- zio-config

**Comment by aleksandarskrbic** [comment]
In progress! 😀
