### ISSUE TITLE
Scan functions have inconsistent API

### ISSUE THREAD

**Issue by justinhj** [zio/zio-redis#208]
The Scan functions, SSCAN for example, take the cursor as a Long but the subsequent cursor in the return value is a String

```
final def sScan(
    key: String,
    cursor: Long,
```

Returns `ZIO[RedisExecutor, RedisError, (String, Chunk[String])]`

This creates a burden on the user to (safely) convert the cursor to a Long for the next iteration. For example:

```
 testM("iterate over multiple scans") {
          for {
            key                <- uuid
            _                  <- sAdd(key, "a", "b", "c", "d", "e")
            scan               <- sScan(key, 0L, count = Some(Count(3L)))
            (cursor, members)   = scan
            scan2              <- sScan(key, cursor.toLong, count = Some(Count(3L)))
            (cursor2, members2) = scan2
          } yield assert(cursor)(isNonEmptyString) &&
            assert(members)(isNonEmpty) &&
            assert(cursor2)(equalTo("0"))
        }
```

**Comment by mijicd** [comment]
Good catch!

**Comment by anovakovic01** [comment]
@justinhj Thanks for the report, if you want to fix it, it should be an easy fix. Just cast string to long in the `ScanOutput`.

**Comment by justinhj** [comment]
@anovakovic01 Sounds good I will give it a shot
