### ISSUE TITLE
API for binary data

### ISSUE THREAD

**Issue by quelgar** [zio/zio-redis#214]
There are many cases where the public API uses `String` where Redis supports arbitrary binary data. To use the Redis parlance, all bulk strings are "binary safe".

Taking the `SET` command for example, Redis supports arbitrary bytes for both the value and the key, meaning we should offer an API along the lines of:

```scala
final def set(
    key: Chunk[Byte],
    value: Chunk[Byte],
    expire: Option[Duration] = None,
    update: Option[Update] = None,
    keepTtl: Option[KeepTtl] = None
  ): ZIO[RedisExecutor, RedisError, Option[Unit]]
```

However, it will be extremely common in practice for users to want to use `String`, so we should continue to make this easy to do. How to best do this?

A simple brute-force method would be to offer two versions of all APIs where this matters, one using `Chunk[Byte]` and another using `String` (which simply passes UTF-8 encoded bytes to the `Chunk[Byte]` variant). I think that means a lot of boilerplate though, and it would not allow mixing and matching: it would be nice if we could do `set("myKey", myJpegBytes)`.

The best idea I've had so far is using typeclasses for encoding decoding. Encoding sketch:

```scala

trait RedisEncoder[A] {
  def encode(a: A): Chunk[Byte]
}

final def set[A: RedisEncoder, B: RedisEncoder](
    key: A,
    value: B,
    expire: Option[Duration] = None,
    update: Option[Update] = None,
    keepTtl: Option[KeepTtl] = None
  ): ZIO[RedisExecutor, RedisError, Option[Unit]] = {
  val keyBytes = implicitly[RedisEncoder[A]].encode(key)
  val valueBytes = implicitly[RedisEncoder[B]].encode(value)
  Set.run((keyBytes, valueBytes, expire, update, keepTtl)) 
}

implicit val identityEncoder: RedisEncoder[Chunk[Byte]] = new RedisEncoder[Chunk[Byte]] {
  def encode(a: Chunk[Byte]) = a
}

implicit val stringEncoder: RedisEncoder[String] = new RedisEncoder[String] {
  def encode(a: String) = Chunk.fromArray(s.getBytes(StandardCharsets.UTF_8))
}
```

**Comment by mijicd** [comment]
I'm absolutely for it. The additional benefit - our API becomes less "stringly" typed. Typeclass approach is fine, we can provide the standard instances in companions and we'd still be adhering to that "have a single import" rule.
