### ISSUE TITLE
Fix `exists` command return type from the Keys api

### ISSUE THREAD

**Issue by gagandeepkalra** [zio/zio-redis#219]
When there are multiple keys, `exists` command can return an integer greater than 1, in that case our code would throw trying to interpret the result to a Boolean.

please refer this [thread](https://github.com/zio/zio-redis/pull/217#discussion_r528308091).

**Comment by gagandeepkalra** [comment]
@mijicd I'd like to attempt this

**Comment by mijicd** [comment]
@gagandeepkalra all yours, thank you :pray:
