### ISSUE TITLE
Change input type arguments from `Long` to `Duration` for time use cases

### ISSUE THREAD

**Issue by gagandeepkalra** [zio/zio-redis#220]
Redis api at times requires `time` values with different precision scales, rather than passing this cognitive load to the user for computing the correct `long` value each time, we can have base input type to be `Duration` instead.

Refer `Keys#{migrate, restore, wait_}`

**Comment by justinhj** [comment]
Will take this

**Comment by anovakovic01** [comment]
Resolved in #230.
