### ISSUE TITLE
Add support for the XINFO command

### ISSUE THREAD

**Issue by anovakovic01** [zio/zio-redis#233]
Add support for the `XINFO [CONSUMERS key groupname] [GROUPS key] [STREAM key] [HELP]` command in order to have full support for the Redis Streams (#157). Tests should also be added for this command.

**Comment by jxnu-liguobin** [comment]
Did anyone pick it up? I'm interested.

**Comment by anovakovic01** [comment]
No one is working on this one at the moment. It's all yours.

**Comment by anovakovic01** [comment]
Resolved by #301.
