### ISSUE TITLE
Add the FULL option to XINFO STREAM command

### ISSUE THREAD

**Issue by anovakovic01** [zio/zio-redis#312]
There is no support for FULL option implemented in `zio-redis`. This is not a priority as it works only with Redis version 6.

**Comment by jxnu-liguobin** [comment]
doing. 

I found that some mainstream clients do not support this option. Because the return structure of this option is extremely complex, I may need a new command.(It's very painful to parse the structure)

**Comment by jxnu-liguobin** [comment]
closed by #323
