### ISSUE TITLE
Mission options for ZADD

### ISSUE THREAD

**Issue by hcwilhelm** [zio/zio-redis#329]
According to the Redis docs ZADD https://redis.io/commands/zadd ZADD supports `[NX|XX] [GT|LT] [CH] [INCR]` options but the current zio-redis implementation only supports `[NX|XX][CH]` options.

We should implement the missing options and write proper tests for them.

**Comment by jxnu-liguobin** [comment]
Has anyone started?

**Comment by hcwilhelm** [comment]
> Has anyone started?

I didn’t start with that you can take it. 👍
