### ISSUE TITLE
Missing command ZDIFF and ZDIFFSTORE

### ISSUE THREAD

**Issue by hcwilhelm** [zio/zio-redis#349]
For the SortedSet API, the commands ZDIFF and ZDIFFSTORE are missing.

https://redis.io/commands/zdiff
https://redis.io/commands/zdiffstore

## Tasks

- [ ] Implement missing commands in the SortedSet API
- [ ] Implement tests
- [ ] Add support for these commands to the test executor

**Comment by rfmejia** [comment]
#367 and #368 are PRs for the different commands (implementation and tests). I just came across #363 for the test executor, if the ZDIFF APIs are different I can modify the PRs.

**Comment by mijicd** [comment]
Closed in #367 and #368
