### ISSUE TITLE
Rewrite the example using ZIO libraries

### ISSUE THREAD

**Issue by mijicd** [zio/zio-redis#415]
With zio-json and zio-http out there, it makes sense to rewrite the example using them.

For the sake of simplicity, the implementer should preserve the existing scenario, i.e., retrieving project contributors via GitHub API. Once the example is ported, we can think about making additional scenarios.

**Comment by mijicd** [comment]
cc @mvelimir

**Comment by paulpdaniels** [comment]
I don't mind taking this one.

**Comment by mijicd** [comment]
@paulpdaniels all yours, thanks!
