### ISSUE TITLE
Implement CLIENT INFO and CLIENT LIST commands

### ISSUE THREAD

**Issue by mvelimir** [zio/zio-redis#460]
## Overview
The library is missing the [CLIENT INFO](https://redis.io/commands/client-info) and [CLIENT LIST](https://redis.io/commands/client-list) commands from the connection API. The client hangs with the current implementation of `RedisExecutor` in regards to those two commands, so `RedisExecutor` would need to be modified in order to support them.
## Tips
* API should be defined in `zio.redis.api.Connection`.
* Command-specific options should be defined in `zio.redis.options.Connection`.
* Additional inputs and outputs can be defined in `zio.redis.Input` and `zio.redis.Output`, respectively.
* Write inputs and outputs tests in `zio.redis.InputSpec` and `zio.redis.OutputSpec`, respectively.
* Write integration tests by expanding the `zio.redis.ApiSpec`.

**Comment by jgoday** [comment]
Hi, I have tried to implement it in this #612
