### ISSUE TITLE
Implement CLIENT REPLY command

### ISSUE THREAD

**Issue by mvelimir** [zio/zio-redis#461]
## Overview
The library is missing the [CLIENT REPLY](https://redis.io/commands/client-reply) command from the connection API. The current implementation of the `RedisExecutor` will need to be modified in order to support the functionality of this command.
## Tips
* API should be defined in `zio.redis.api.Connection`.
* Command-specific options should be defined in `zio.redis.options.Connection`.
* Additional inputs and outputs can be defined in `zio.redis.Input` and `zio.redis.Output`, respectively.
* Write inputs and outputs tests in `zio.redis.InputSpec` and `zio.redis.OutputSpec`, respectively.
* Write integration tests by expanding the `zio.redis.ApiSpec`.
* Implement commands in the `TestExecutor`.

**Comment by drmarjanovic** [comment]
None of  **lettuce**, **redis4cats**, **scredis**, **scala-redis**, and **laserdisc** libraries supports `CLIENT REPLY` command. So, at the moment, we are going to close this issue.
