### ISSUE TITLE
Upgrade to ZIO 2.0

### ISSUE THREAD

**Issue by swoogles** [zio/zio-redis#462]
ZIO 2.0 is at Milestone 4, with an RC expected in the next few weeks.
https://github.com/zio/zio/releases/tag/v2.0.0-M4

The API is nearly stable at this point, so any early migration work against this version should pay off towards the official 2.0 release.

The progress is being tracked here:
zio/zio#5470

The Stream Encoding work in progress is the only area where the API might still change before the RC.

We are actively working on a ScalaFix rule that will cover the bulk of the simple API changes:
https://github.com/zio/zio/blob/series/2.x/scalafix/rules/src/main/scala/fix/Zio2Upgrade.scala
We highly recommend starting with that, and then working through any remaining compilation errors :)

To assist with the rest of the migration, we have created this guide:
https://zio.dev/howto/migrate/zio-2.x-migration-guide/

If you would like assistance with the migration from myself or other ZIO contributors, please let us know!

**Comment by mijicd** [comment]
@swoogles Sorry for the delayed response. This is definitely on my radar, especially having in mind the potential improvements to the RedisExecutor. My priority at the moment is to finally wrap up #404, and as soon as that's done, I'm taking care of 2.x compat.

**Comment by mijicd** [comment]
@swoogles this needs to be postponed until zio-schema adds support for 2.x.

**Comment by subotic** [comment]
@mijicd Great library. Thanks for all the work. Can't wait to make the move to it in our backend as soon as ZIO 2.x is supported.

**Comment by jxnu-liguobin** [comment]
@mijicd Is it time to upgrade zio 2.0? Or has someone already doing it?

**Comment by mijicd** [comment]
No one is doing it right now. I believe all the deps are 2.x compatible,
so, if you want it, go for it. Just make sure to keep it on series/2.x
branch.

**Comment by jxnu-liguobin** [comment]
@mijicd The main work is done, but now it can't create connection and need help as pr show.
