### ISSUE TITLE
Please add this good library to maven center

### ISSUE THREAD

**Issue by zhiwilliam** [zio/zio-redis#593]
I like your library and want to introduce it to my project, but I found I cannot import it directly from sbt. So please help me to resolve it.

**Comment by jxnu-liguobin** [comment]
> I like your library and want to introduce it to my project, but I found I cannot import it directly from sbt. So please help me to resolve it.

The project has not been officially released. At present, only snapshot can be used.😂

**Comment by mijicd** [comment]
As suggested by @jxnu-liguobin the library is available as snapshot only at the moment. Unfortunately, my availability delayed the official release massively, but I'll try to get it on track.
