### ISSUE TITLE
Test hashes API

### ISSUE THREAD

**Issue by mijicd** [zio/zio-redis#60]
Expand the [ApiSpec](https://github.com/zio/zio-redis/blob/master/src/test/scala/zio/redis/ApiSpec.scala) with hashes commands.

**Comment by aleksandarskrbic** [comment]
I'm taking this one!

**Comment by mijicd** [comment]
@aleksandarskrbic do you need any help with this one?

**Comment by aleksandarskrbic** [comment]
@mijicd I finished ~70% of works, hope that I will submit PR until Friday since I was pretty busy last 2 weeks :)

**Comment by mijicd** [comment]
Awesome!
