### ISSUE TITLE
BulkString with newline character at the end causes process to lock

### ISSUE THREAD

**Issue by jgoday** [zio/zio-redis#613]
If a bulkString has a '\n' at the end of the actual string data, RespValue Decoder produces a lock in the current RedisExecutor.

One way to reproduce it is using PING command that returns a BulkString if a string argument is provided.
```scala
testM("PING with a string argument will lock executor") {
  ping(Some("Hello with a newline\n")).map(assert(_)(equalTo("Hello with a newline\n")))
}
```
Executing it (bloop test redis-test -- -t "PING with a string argument will lock executor"),
will cause a timeout exception (Timeout of 1 m exceeded.)

I was facing this issue trying to implement #612 (decoding a client info response returned from the server as a bulk string, client info data has a newline char at the end of the record).

I think the problem is located at RespValue Decoder
```scala
Transducer.utf8Decode >>> Transducer.splitLines >>> processLine
```

Transduder.splitLines will produce an empty line after the bulk string data,
causing an incosistent state in the feed method,
when the bulk string data is completed, state becomes 'Done' and then, with the new empty line, it becomes 'Failed'.

A simple solution seems to have a transition from 'Start' to 'Start' when a empty line is feeded.

Could make a PR if it makes sense.

**Comment by mijicd** [comment]
Hi, sorry for an **extremely delayed** response. If you have already played with a bugfix, please submit it. I'd be happy to help with it.
