### ISSUE TITLE
Test lists API

### ISSUE THREAD

**Issue by mijicd** [zio/zio-redis#62]
Expand the [ApiSpec](https://github.com/zio/zio-redis/blob/master/src/test/scala/zio/redis/ApiSpec.scala) with lists commands.

**Comment by geoffjohn11** [comment]
I can add tests for the lists api

**Comment by mijicd** [comment]
@geoffjohn11 all yours, let me know if you need any help!

**Comment by geoffjohn11** [comment]
Thanks @mijicd for offering to help!  I created a pr with my attempt: https://github.com/zio/zio-redis/pull/80

**Comment by mijicd** [comment]
Closed in #80
