### ISSUE TITLE
Benchmark the implementation

### ISSUE THREAD

**Issue by mijicd** [zio/zio-redis#66]
Benchmark the performance of the API using JMH. Benchmarks should include the other client libraries (e.g. redis4cats and laserdisc-io).

**Comment by mikail-khan** [comment]
redis4cats is just a cats wrapper for [lettuce](https://github.com/lettuce-io/lettuce-core)

**Comment by mijicd** [comment]
@mikail-khan I am aware of that. Still it is used, so I think it's worth having it. I'm open to including others as well.

**Comment by mijicd** [comment]
Splitted.
