### ISSUE TITLE
Fix DUMP command

### ISSUE THREAD

**Issue by mijicd** [zio/zio-redis#78]
Dump response can't be parsed. Find the root cause and "unignore" the existing test.

**Comment by shankarshastri** [comment]
@mijicd , I actually spend a good amount of time on this issue. Found that there are differences in the serialized byte string.

<img width="1792" alt="Screenshot 2020-08-23 at 6 02 12 PM" src="https://user-images.githubusercontent.com/10391044/90978360-f94ba600-e56a-11ea-99e8-e974050aac69.png">

Note: In the above image the commands monitored are from zio-redis tests, and the next one is done manually. 

I shall continue to investigate.

**Comment by shankarshastri** [comment]
Few characters that Redis responds for dump output when converted to utf8 byte string there's a mismatch in the bytes. 
Either we need to make DUMP command respond back with Array[Byte] or we need to try different charset for DUMP alone. I have created a draft branch for trying out things. Please check the same.

@mijicd, Please let me know your thoughts.

**Comment by mijicd** [comment]
@shankarshastri thankd for taking care of this, I'll take a look at it a bit later!

**Comment by mijicd** [comment]
@shankarshastri Let's try to minimize the impact and replace the output type to `Chunk[Byte]` rather than changing encoding.

**Comment by shankarshastri** [comment]
@mijicd , if you can actually provide me few hints on how I should start I can go ahead. I have few doubts, as currently the unsafeReceive method returns the string rather than chunk[bytes]. Please let me know your thoughts.

**Comment by mijicd** [comment]
@shankarshastri Ah yes, you are right. Let me think about this one a bit and I'll get back to you.

**Comment by mijicd** [comment]
@shankarshastri Let's give it a try and actually expose the raw stuff from interpreter. So, what you need to do is:

- Avoid conversion to string in `RedisExecutor#unsafeReceive`.
- Adjust all signatures.
- Convert to string where applicable (all commands but `dump`).
- Modify `Output` decoding.

**Comment by shankarshastri** [comment]
Sure @mijicd, I shall spend some time this week.

**Comment by shankarshastri** [comment]
@mijicd , I was trying to make the changes, but then for `restore` command as well the input will change right? And currently, `Input` `encode` method is returning Chunk[String]. Please let me know your thoughts !!

**Comment by mijicd** [comment]
@shankarshastri Yes. Give it a timeboxed try, if it causes a severe disruption, it easier to temporary remove support and check out the implementation in well established libraries like lettuce.

**Comment by shankarshastri** [comment]
Sure !!

**Comment by quelgar** [comment]
I'll tackle this for the Hackathon.
