### ISSUE TITLE
Fix KEYS command

### ISSUE THREAD

**Issue by mijicd** [zio/zio-redis#79]
Keys response can't be parsed once there is more than 24 keys as pointed in #74. Whoever picks this ticket should fix the issue and "unignore" the existing test.

**Comment by msvaljek** [comment]
I'll take this one!

**Comment by mijicd** [comment]
Somewhat related, keys test was failing for quite a lot as part of https://github.com/zio/zio-redis/pull/80. See [this](https://app.circleci.com/pipelines/github/zio/zio-redis/193/workflows/8e0388c1-2086-40b5-81ff-85e273ee7342/jobs/1155).

**Comment by mijicd** [comment]
Closed in #87.
