### ISSUE TITLE
 how to do redis-cli --tls through the code

### ISSUE THREAD

**Issue by alek-w** [zio/zio-redis#958]
redis-cli -h master.somethng-somethng-somethng.somethng.amazonaws.com -p 6379 --tls -a passss

could you tell pls how to do the same through the code?

https://github.com/zio/zio-redis/blob/master/modules/redis/src/main/scala/zio/redis/api/Connection.scala#L36

**Comment by victornguen** [comment]
You can authorize in Redis after constructing your ZLayer containing Redis. 
For example:
```scala
Redis.singleNode.tap { redis: ZEnvironment[Redis] =>
    ZIO.attempt {
      redis.get.auth("password")
    }
  }
```
