### ISSUE TITLE
what is the configuration file?

### ISSUE THREAD

**Issue by alek-w** [zio/zio-redis#959]
https://github.com/zio/zio-redis/blob/master/modules/redis/src/main/scala/zio/redis/api/Connection.scala#L36  

it says 

if the password provided via AUTH matches the password in the configuration file, the Unit value is returned and the server starts accepting commands. Otherwise, an error is returned and the client needs to try a new password.

but what is the configuration file? thx in advance

**Comment by victornguen** [comment]
Hi!
I think the mentioned configuration file is the Redis config (redis.conf) or a separate ACL file with user credentials. 
You can use the `auth` method to authenticate with any credentials that are in the ACL.
